src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $text;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'posts')]
    private $category;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'posts')]
    #[ORM\JoinColumn(nullable: false)]
    private $user_id;

    #[ORM\OneToMany(mappedBy: 'post_id', targetEntity: Comment::class)]
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function user()
    {
        return '';
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPostId($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPostId() === $this) {
                $comment->setPostId(null);
            }
        }

        return $this;
    }
}

templates/blogs/index.html.twig
{% extends 'layouts/base.html.twig' %}

{% block content %}
    <h1>Posts List</h1>

    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        <h2><a href="{{ path('posts.add') }}">Add a post</a></h2>
    {% endif %}

    <ul>
        {% for post in posts %}
            <li>
                <h3>{{ post.title }}</h3>
                <p>{{ post.text }}</p>
                <a href="{{ path('posts.show', {'id': post.id}) }}">View Post</a>
                {% if post.category is not null %}
                    <p>Post category: {{ post.category.name }}</p>
                {% endif %}
                <hr>
            </li>
        {% endfor %}
    </ul>
    
{% endblock %}

templates/blogs/new.html.twig
{% extends 'layouts/base.html.twig' %}

{% block content %}
    {{ form(form) }}
{% endblock %}

templates/blogs/view.html.twig
{% extends 'layouts/base.html.twig' %}

{% block content %}
    <h3>{{ post.title }}</h3>
    <hr>
    <p>{{ post.text }}</p>
    <ul>
        {% for comment in comments %}
            <li>{{ comment.userId.email }} comments: {{ comment.body }}</li>
            {% if is_granted('ROLE_ADMIN') or comment.userId.id == app.user.id %}
                <a href="{{ path('comments.delete', {'id': comment.id}) }}">Delete</a>
                <a href="{{ path('comments.edit', {'id': comment.id}) }}">Edit</a>
            {% endif %}
        {% endfor %}
    </ul>

    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        <h4>Add a comment:</h4>
        <form action="{{ path('comments.add') }}">
            <input type="text" name="body">
            <input type="hidden" name="post_id" value="{{ post.id }}">
            <button type="submit">Comment!</button>
        </form>
    {% endif %}
{% endblock %}